# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html

image: node:latest

cache:
  paths:
    - node_modules/

run-tests:
  script:
    - npm ci
    - npm run test:coverage
